<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
    <title>Copy Paste PDF Text Fixer</title>
</head>
<body>
    <h1>Copy Paste PDF Text Fixer</h1>
    <p>This page simply remove extra newlines and spaces typically found in copy-pasted text taken from a PDF file.</p>
    <p><strong>UNLICENSED. THIS CODE IS GENERATED BY ChatGPT.</strong></p>
    <form method="post" action="">
        <label for="inputText">Input Text:</label><br>
        <textarea id="inputText" name="inputText" rows="10" cols="50"><?php echo isset($_POST['inputText']) ? htmlspecialchars($_POST['inputText']) : ''; ?></textarea><br><br>
        <input type="submit" value="Format Text">
    </form>

    <?php
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $inputText = $_POST['inputText'];

        // Replace newlines with spaces and reduce multiple spaces to a single space
        $outputText = preg_replace('/\s+/', ' ', str_replace("\n", ' ', $inputText));

        echo '<h2>Formatted Text:</h2>';
        echo '<textarea rows="10" cols="50">' . htmlspecialchars($outputText) . '</textarea>';
    }
    ?>
</body>
</html>
