<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
    <title>Formatted Text</title>
</head>
<body>
    <h1>Formatted Text</h1>
    <p>This page displays the formatted text.</p>
    <p><strong>UNLICENSED. THIS CODE IS GENERATED BY ChatGPT.</strong></p>

    <?php
    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        $inputText = $_POST['inputText'];

        // Replace newlines with spaces and reduce multiple spaces to a single space
        $outputText = preg_replace('/\s+/', ' ', str_replace("\n", ' ', $inputText));

        echo '<h2>Formatted Text:</h2>';
        echo '<textarea rows="10" cols="50">' . htmlspecialchars($outputText) . '</textarea>';
    }
    ?>

    <br><br>
    <a href="index.html">Go Back</a>
</body>
</html>
